// Writes a build timestamp into src/version.ts before each build/dev run.
const fs = require('fs');
const path = require('path');

const ts = Date.now();
const out = `// Auto-generated by scripts/stamp.js — do not edit.\nexport const BUILD_TIME = ${ts};\n`;
fs.writeFileSync(path.join(__dirname, '../src/version.ts'), out);
console.log(`[stamp] Build time: ${new Date(ts).toISOString()}`);
